### ISSUE TITLE
RegistrarConsoleScreenshotTest 

### ISSUE THREAD

**Issue by amsyvah** [google/nomulus#2345]
#5 transferring context: 101B done
#5 DONE 0.0s

#6 [2/2] ADD build/libs/nomulus.jar /nomulus.jar
#6 CACHED

#7 exporting to image
#7 exporting layers done
#7 writing image sha256:d250898bf35d75d42d1493dbf87007bd593179a391ce33f27114439ac63f27c4 done
#7 naming to docker.io/library/nomulus-tool done
#7 DONE 0.0s
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :core:fragileTest

RegistrarConsoleScreenshotTest > settingsContact_asAdmin() > [3] FAILED
    org.gradle.internal.exceptions.DefaultMultiCauseException at RetryingTestExtension.java:167
        Caused by: org.opentest4j.TestAbortedException at RetryingTestExtension.java:161
            Caused by: java.util.concurrent.TimeoutException at ForEachOps.java:184
<======-------> 52% EXECUTING [11m 47s]

RegistrarConsoleScreenshotTest > settingsContactEdit_setRegistryLockPassword() > [3] FAILED
    org.gradle.internal.exceptions.DefaultMultiCauseException at RetryingTestExtension.java:167
        Caused by: org.opentest4j.TestAbortedException at RetryingTestExtension.java:161
            Caused by: java.util.concurrent.TimeoutException at ForEachOps.java:184

RegistrarConsoleScreenshotTest > getOteStatus_completed() > [3] FAILED
    org.gradle.internal.exceptions.DefaultMultiCauseException at RetryingTestExtension.java:167
        Caused by: org.opentest4j.TestAbortedException at RetryingTestExtension.java:161
            Caused by: java.util.concurrent.TimeoutException at ForEachOps.java:184

<======-------> 52% EXECUTING [22m 22s]
> :core:fragileTest > 47 tests completed, 3 failed, 6 skipped
> :core:fragileTest > Executing test google.registry.webdriver.RegistrarConsoleScreenshotTest
![Screenshot from 2024-03-04 01-32-38](https://github.com/google/nomulus/assets/24782156/785911bb-38c1-4838-94f5-a5843b8d6e4a)

#### The attached screenshot is from a previous attempt moments ago.  On repeated attempts, it hangs approximately at 52% EXECUTING,  for lengths of time as much as 40 minutes as I have seen;  Tried running the command with sudo, even as root, the results do not vary.  Perhaps an access issue for some componets of the Google Cloud in trial mode ?   ####

( Twice I interuppted after a long wait with ^C, these are the erros messages on interrupt:

> :core:fragileTest > Executing test google.registry.webdriver.RegistrarConsoleScreenshotTest
^CTraceback (most recent call last):
  File "/home/s/workingdir/workingdir/nomulus/./config/nom_build.py", line 425, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/s/workingdir/workingdir/nomulus/./config/nom_build.py", line 420, in main
    return subprocess.call(gradle_command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 391, in call
    return p.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2046, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2004, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Comment by amsyvah** [comment]
Adding another screenshot from another attempt to complete the installation: After 1 hour 50 minutes,  it is still at the same 52%, except that the number of tests completed, failed and skipped are respectively 101, 20 and 40.

![Screenshot from 2024-03-04 04-00-18](https://github.com/google/nomulus/assets/24782156/d9338c19-ad26-45d3-8826-00bd7d44765d)

**Comment by amsyvah** [comment]
`^C` interrupt produces similar or the same errors:

> :core:fragileTest > 102 tests completed, 20 failed, 41 skipped
> :core:fragileTest > Executing test google.registry.webdriver.RegistrarConsole
^CTraceback (most recent call last):
  File "/home/s/workingdir/workingdir/nomulus/./config/nom_build.py", line 425, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/s/workingdir/workingdir/nomulus/./config/nom_build.py", line 420, in main
    return subprocess.call(gradle_command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 391, in call
    return p.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2046, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2004, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Comment by jianglai** [comment]
I would recommend just to exclude the screenshot tests. They are flaky and the code they are testing are deprecated and will be removed soon.
