### ISSUE TITLE
SessionKeyExposingObjectify getSession().keys()  issues

### ISSUE THREAD

**Issue by a5825799** [google/nomulus#73]

**Comment by a5825799** [comment]
import com.google.common.collect.ImmutableSet;
import com.googlecode.objectify.Key;
import com.googlecode.objectify.ObjectifyFactory;
import com.googlecode.objectify.impl.ObjectifyImpl;

/** Registry-specific Objectify subclass that exposes the keys used in the current session. */
public class SessionKeyExposingObjectify extends ObjectifyImpl<SessionKeyExposingObjectify> {

  public SessionKeyExposingObjectify(ObjectifyFactory factory) {
    super(factory);
  }

  /** Expose the protected method that provides the keys read, saved or deleted in a session. */
  ImmutableSet<Key<?>> getSessionKeys() {
    return ImmutableSet.copyOf(getSession().keys());
  }
}
this is a objectifyV4 methods, why objectifyV5 methods,有什么解决方式么？

**Comment by jianglai** [comment]
I am not sure I understand what you are asking. We currently only support Objectify 4.

**Comment by CydeWeys** [comment]
To expand on this, we started writing the codebase in 2012, long before Objectify 5 had been released.  The project was only imported into Github more recently, so you can't see that history.  But we definitely would have used v5 had it been around when we started.

The gains from migrating now aren't very large, and it would be painful to do so on a running system, so we haven't done so.

**Comment by a5825799** [comment]
Thank you for your reply.
This is a new problem I encountered when creating suffixes.
[root@nomulus tools]# ./nomulus  -e alpha create_tld example --roid_suffix EXAMPLE --initial_tld_state GENERAL_AVAILABILITY --tld_type TEST
Aug 11, 2018 7:09:44 AM google.registry.config.YamlUtils mergeYaml
WARNING: Ignoring empty environment configuration YAML file.
Aug 11, 2018 7:09:46 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Aug 11, 2018 7:09:46 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Aug 11, 2018 7:09:46 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Aug 11, 2018 7:09:46 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Aug 11, 2018 7:09:46 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Aug 11, 2018 7:09:46 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:477)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:153)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
        at com.google.appengine.tools.remoteapi.StandaloneAppEngineClient.doGet(StandaloneAppEngineClient.java:44)
        at com.google.appengine.tools.remoteapi.StandaloneAppEngineClient.get(StandaloneAppEngineClient.java:34)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.getAppIdFromServer(RemoteApiInstaller.java:411)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.loginImpl(RemoteApiInstaller.java:374)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.login(RemoteApiInstaller.java:335)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.install(RemoteApiInstaller.java:171)
        at google.registry.tools.RegistryCli.runCommand(RegistryCli.java:202)
        at google.registry.tools.RegistryCli.run(RegistryCli.java:152)
        at google.registry.tools.RegistryTool.main(RegistryTool.java:131)
        Suppressed: java.lang.IllegalArgumentException: remote API is already uninstalled
                at com.google.appengine.tools.remoteapi.RemoteApiInstaller.uninstall(RemoteApiInstaller.java:253)
                at google.registry.tools.RegistryCli.close(RegistryCli.java:163)
                at google.registry.tools.RegistryTool.main(RegistryTool.java:132)
