### ISSUE TITLE
When I created the suffix, I reported that the Connection refused,Is it necessary to install a remote API?

### ISSUE THREAD

**Issue by a5825799** [google/nomulus#74]
[root@nomulus tools]# ./nomulus -e alpha list_registrars
Aug 11, 2018 8:10:36 AM google.registry.config.YamlUtils mergeYaml
WARNING: Ignoring empty environment configuration YAML file.
Aug 11, 2018 8:10:38 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Aug 11, 2018 8:10:38 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Aug 11, 2018 8:10:38 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Aug 11, 2018 8:10:38 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Aug 11, 2018 8:10:38 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Aug 11, 2018 8:10:38 AM com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:477)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:153)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
        at com.google.appengine.repackaged.org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
        at com.google.appengine.tools.remoteapi.StandaloneAppEngineClient.doGet(StandaloneAppEngineClient.java:44)
        at com.google.appengine.tools.remoteapi.StandaloneAppEngineClient.get(StandaloneAppEngineClient.java:34)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.getAppIdFromServer(RemoteApiInstaller.java:411)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.loginImpl(RemoteApiInstaller.java:374)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.login(RemoteApiInstaller.java:335)
        at com.google.appengine.tools.remoteapi.RemoteApiInstaller.install(RemoteApiInstaller.java:171)
        at google.registry.tools.RegistryCli.runCommand(RegistryCli.java:202)
        at google.registry.tools.RegistryCli.run(RegistryCli.java:152)
        at google.registry.tools.RegistryTool.main(RegistryTool.java:131)
        Suppressed: java.lang.IllegalArgumentException: remote API is already uninstalled
                at com.google.appengine.tools.remoteapi.RemoteApiInstaller.uninstall(RemoteApiInstaller.java:253)
                at google.registry.tools.RegistryCli.close(RegistryCli.java:163)
                at google.registry.tools.RegistryTool.main(RegistryTool.java:132).
Are there any specific documents for installing the remote API?

**Comment by a5825799** [comment]
[root@nomulus files]# cat nomulus-config.yaml 
appEngine:
  # Globally unique App Engine project ID
  projectId: bjguoxu-registry-alpha

  # Hostname and port of the tools service for the project.
  toolsServiceUrl:
    hostName: 18.222.132.99
    port: 443
oAuth:
  allowedOauthClientIds:[client_secret_90002340567-jm9eehkmjnaoi276r46scaq270tludhm.apps.googleusercontent.com.json]
This is my configuration in nomulus-config.yaml

**Comment by a5825799** [comment]
[root@nomulus files]# cat nomulus-config.yaml 
appEngine:
  # Globally unique App Engine project ID
  projectId: bjguoxu-registry-alpha

  # Hostname and port of the tools service for the project.
  toolsServiceUrl:
    hostName: 18.222.132.99
    port: 443
oAuth:
  allowedOauthClientIds:[client_secret_90002340567-jm9eehkmjnaoi276r46scaq270tludhm.apps.googleusercontent.com.json]
This is my configuration in nomulus-config.yaml.

**Comment by a5825799** [comment]
[root@nomulus files]# cat nomulus-config.yaml 
appEngine:
  projectId: bjguoxu-registry-alpha

  toolsServiceUrl:
    hostName: 18.222.132.99
    port: 443
oAuth:
  allowedOauthClientIds:[client_secret_90002340567-jm9eehkmjnaoi276r46scaq270tludhm.apps.googleusercontent.com.json]
This is my configuration in nomulus-config.yaml.

**Comment by a5825799** [comment]
This is a mistake prompted：
===================================================================
You must login using 'nomulus login' prior to running this command.
===================================================================
